steps:
  # 1. LINTING
  - name: 'python:3.11-slim'
    id: 'Linting'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install ruff
        ruff check .

  # 2. TESTS
  - name: 'python:3.11-slim'
    id: 'Unit-Tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt pytest
        if [ -d "tests" ]; then pytest tests/; else echo "No hay tests"; fi

  # 3. BUILD
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build-Image'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dog-scanner-repo/backend-image:$COMMIT_SHA', '.']

  # 4. PUSH
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push-Image'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/dog-scanner-repo/backend-image:$COMMIT_SHA']

  # 5. DEPLOY
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dog-scanner-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/dog-scanner-repo/backend-image:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest'
  # 6. BUILD FRONTEND
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build-Frontend'
    args: ['build', '-f', 'Dockerfile.frontend', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dog-scanner-repo/frontend-image:$COMMIT_SHA', '.']

  # 7. PUSH FRONTEND
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push-Frontend'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/dog-scanner-repo/frontend-image:$COMMIT_SHA']

  # 8. DEPLOY FRONTEND
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy-Frontend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dog-scanner-web'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/dog-scanner-repo/frontend-image:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/dog-scanner-repo/backend-image:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/dog-scanner-repo/frontend-image:$COMMIT_SHA'

options:
  logging: 'CLOUD_LOGGING_ONLY'